defaults: &defaults
  max_failed_login_attempts: -1 # disabled
  failed_login_lock_timeout: 5 # minutes a user gets locked for when using max_failed_login_attempts
  service_ticket:
    lifetime_unconsumed: 299
  authenticators:
    static_1:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"
            name: "Test User"
    static_2:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          example:
            password: "dito123"
            name: "Test User"

development:
  <<: *defaults

test:
  <<: *defaults
